install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

build:
  project: NHtmlUnit.sln

test:
  assemblies:
    - 'tests/**/bin/*/*Tests.dll'